apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  Name: hello-world
  namespace: argo-workflows
spec:
  entrypoint: hello
  templates:
    - name: hello
      container:
        image: alpine:3.14
        command: [echo]
        args: ["Hello World"]