server:
  enabled: true
  extraArgs:
    - --auth-mode=server
    - --no-auth

  # Disable default authentication methods
  authModes:
    client: false
    server: true
    sso: false

workflow:
  serviceAccount:
    create: true
    name: "argo-workflow"

  rbac:
    create: true

controller:
  enabled: true
  containerRuntimeExecutor: docker
  workflowNamespaces:
    - default

# Disable default SSO configurations
sso:
  enabled: false

# Disable RBAC for UI access
useDefaultArtifactRepo: false
useStaticCredentials: false

# Optional but recommended: Configure service type
service:
  type: ClusterIP  # Change to NodePort or LoadBalancer based on your needs

# Persistence configuration (optional)
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 20Gi