server:
  enabled: true
  extraArgs:
    - --auth-mode=server
    - --no-auth

  # Add GKE managed certificate configuration
  GKEmanagedCertificate:
    enabled: false  # Disable GKE managed certificate if not needed

  # Disable default authentication methods
  authModes:
    client: false
    server: true
    sso: false

workflow:
  serviceAccount:
    create: true
    name: "argo-workflow"

  rbac:
    create: true

controller:
  enabled: true
  containerRuntimeExecutor: docker
  workflowNamespaces:
    - default

# Disable default SSO configurations
sso:
  enabled: false

# Disable RBAC for UI access
useDefaultArtifactRepo: false
useStaticCredentials: false

service:
  type: ClusterIP

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 20Gi